### ISSUE TITLE
make 会出现 PHP_FE_END 的错误

### ISSUE THREAD

**Issue by sdlla** [NauxLiu/opencc4php#1]
[root@localhost opencc4php]# make
/bin/sh /var/www/html/opencc4php/libtool --mode=compile cc  -I. -I/var/www/html/opencc4php -DPHP_ATOM_INC -I/var/www/html/opencc4php/include -I/var/www/html/opencc4php/main -I/var/www/html/opencc4php -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/usr/include/opencc  -DHAVE_CONFIG_H  -g -O2   -c /var/www/html/opencc4php/opencc.c -o opencc.lo 
libtool: compile:  cc -I. -I/var/www/html/opencc4php -DPHP_ATOM_INC -I/var/www/html/opencc4php/include -I/var/www/html/opencc4php/main -I/var/www/html/opencc4php -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/usr/include/opencc -DHAVE_CONFIG_H -g -O2 -c /var/www/html/opencc4php/opencc.c  -fPIC -DPIC -o .libs/opencc.o
/var/www/html/opencc4php/opencc.c: In function 'zif_opencc_close':
/var/www/html/opencc4php/opencc.c:79:16: warning: initialization makes pointer from integer without a cast [enabled by default]
/var/www/html/opencc4php/opencc.c: In function 'zif_opencc_error':
/var/www/html/opencc4php/opencc.c:105:6: warning: assignment discards 'const' qualifier from pointer target type [enabled by default]
/var/www/html/opencc4php/opencc.c: At top level:
/var/www/html/opencc4php/opencc.c:212:2: error: 'PHP_FE_END' undeclared here (not in a function)
make: *** [opencc.lo] Error 1

make 会出现 PHP_FE_END 的错误
我在网上查到的资料都是屏蔽掉，如：
//PHP_FE_END
{NULL,NULL,NULL}

但还是无法正常运作，请问要如何排除，谢谢
CentOS 6.6
PHP 5.3.3

**Comment by NauxLiu** [comment]
在 php_opencc.h 文件添加下面的代码试试看
```
#ifndef PHP_FE_END
#define PHP_FE_END {NULL, NULL, NULL}
#endif
```
不行我再下载老版本的 Centos 调整。

**Comment by NauxLiu** [comment]
可以参考下这篇问答 http://serverfault.com/questions/317463/php-fe-function-c-error-when-trying-to-enable-extension

**Comment by sdlla** [comment]
安装成功了，感恩

**Comment by NauxLiu** [comment]
@sdlla 你的解决方案可以贴出来吗，方便后面遇到问题的人可查询。

**Comment by sdlla** [comment]
抱歉，就是用你的提供的方法，在 php_opencc.h 后面加上
#ifndef PHP_FE_END
#define PHP_FE_END {NULL, NULL, NULL}
#endif

**Comment by NauxLiu** [comment]
@sdlla 好的。
