### ISSUE TITLE
使用结束后不调用opencc_close会有不良影响吗？

### ISSUE THREAD

**Issue by mmdtl** [NauxLiu/opencc4php#14]
正常的http请求，使用单例模式，处理请求结束后不调用opencc_close会有不良后果吗？如果用在命令行模式下，会有不良后果吗？

**Comment by shtse8** [comment]
還是養成良好的習慣自己關閉，總好過讓系統強制自動回收，長遠下來可減少資源因系統的失效而浪費資源。
