### ISSUE TITLE
太占内存了，4G内存完全不够占的，使用了opencc_close

### ISSUE THREAD

**Issue by tooktoo** [NauxLiu/opencc4php#15]
$od = opencc_open("s2twp.json");
opencc_close($od);
就是不释放内存~！

**Comment by pkujhd** [comment]
@tooktoo 我看了下opencc4php的实现，代码在104行(如果你使用的是php7.0+）有memleak， 将这个语句Z_TYPE_INFO_P(zod) = IS_NULL;换成zend_list_close(Z_RES_P(zod)); 这个语句会造成56bytes的泄露(php7)，如果是php5的话， 修改102行为 zend_list_delete(Z_RESVAL_P(zod)); 
@NauxLiu， zod是php层传递进来的变量，这个的析构应该是自己的zend负责处理的， 不需要处理成IS_NULL的类型.

**Comment by NauxLiu** [comment]
已修复： #17

**Comment by tooktoo** [comment]
@pkujhd 感谢，能把你邮件发给我吗？我还想向你咨询点问题。谢谢

**Comment by pkujhd** [comment]
@tooktoo , 我的email是pkujhd@gmail.com
