### ISSUE TITLE
安装完成后无法打开opencc.php

### ISSUE THREAD

**Issue by seo1214** [NauxLiu/opencc4php#2]
安装完成后无法打开opencc.php
nginx log:
2015/10/25 09:00:48 [error] 28219#0: *1172 FastCGI sent in stderr: "PHP message: PHP Warning:  dl(): Dynamically loaded extensions aren't enabled in /home/html/opencc4php/opencc.php on line 5
PHP message: PHP Warning:  Invalid argument supplied for foreach() in /home/html/opencc4php/opencc.php on line 10
PHP message: PHP Fatal error:  Call to undefined function opencc_error() in /home/html/opencc4php/opencc.php on line 14" while reading response header from upstream, client: 114.111.167.7, server: opencc4php.com, request: "GET /opencc.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "opencc4php.com"

**Comment by NauxLiu** [comment]
这段代码只能在 cli 下面跑，把这段代码删除掉试试
https://github.com/NauxLiu/opencc4php/blob/master/opencc.php#L4-L6

**Comment by seo1214** [comment]
试了还是不行呀。。。

**Comment by NauxLiu** [comment]
@seo1214 贴一下使用的 PHP 版本和具体报错信息。
