### ISSUE TITLE
无法编译通过啊。。。CentOS7.2+PHP7.1.0

### ISSUE THREAD

**Issue by NicolJiang** [NauxLiu/opencc4php#26]
OpenCC的安装方法是：yum install opencc
查了一下安装目录是：/usr/share/opencc

编译错误是：执行make时返回，make: *** 没有指明目标并且找不到 makefile。 停止。

请问要怎么编译啊？

**Comment by pkujhd** [comment]
php extension的正常编译流程需要先调用phpize初始化，然后调用configure --with-php-config产生Makefile
