### ISSUE TITLE
老是出现这个错误怎么搞。

### ISSUE THREAD

**Issue by tooktoo** [NauxLiu/opencc4php#3]
mkdir -p build/rel
(cd build/rel; cmake \
-DBUILD_DOCUMENTATION:BOOL=ON \
-DENABLE_GTEST:BOOL=OFF \
-DCMAKE_BUILD_TYPE=Release \
-DCMAKE_INSTALL_PREFIX=/usr \
../..)
/bin/sh: line 1: cmake: command not found
make: *** [build] Error 127

**Comment by NauxLiu** [comment]
先安装 cmake

**Comment by tooktoo** [comment]
安装了，估计是地址没有装对还是怎么的。现在正在装opencc了。搞了一天了。联系你邮箱，回复都没有！还好这里有。你这个看起来很强大。先用用，也不知道占不占资源！本想想用js转换的。想看看你这个效果！

**Comment by tooktoo** [comment]
![qq 20151028195127](https://cloud.githubusercontent.com/assets/12507122/10787658/787d1754-7dad-11e5-9942-b9053d7e94b1.png)
![qq 20151028195159](https://cloud.githubusercontent.com/assets/12507122/10787668/86472bfe-7dad-11e5-80f4-169ad25c7bcb.png)
 我也蛋痛了，一会可以make一会又不行了
