### ISSUE TITLE
PHP 7.0.19 编译的时候报错

### ISSUE THREAD

**Issue by verchielxy** [NauxLiu/opencc4php#30]
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opencc4php/modules/opencc.so' - libopencc.so.2: cannot open shared object file: No such file or directory in Unknown on line 0

**Comment by pkujhd** [comment]
检查下你的opencc的lib目录下的libopencc是否存在，我在CentOS 6.5上测试没有发现问题
