### ISSUE TITLE
安装成功，运行失败

### ISSUE THREAD

**Issue by plutosuncuan** [NauxLiu/opencc4php#36]
OpenCC
OpenCC4php
都安装成功，但使用
$od = opencc_open("s2twp.json");
报错，直接就是Call to undefined function opencc_open()，
重启php-fpm、nginx都一样报这个错，这是什么原因？

**Comment by pkujhd** [comment]
你将opencc.so 加到php.ini里了么？php -m 确认一下

**Comment by plutosuncuan** [comment]
呃，手动加了，可以了
