### ISSUE TITLE
 libopencc.so.2: cannot open shared object file

### ISSUE THREAD

**Issue by tooktoo** [NauxLiu/opencc4php#5]
确实不懂liunx太多
使用 php -m | grep open 看到没有开启

然后我在php.ini在加了这个模块 但是提示是这个
PHP Warning:  PHP Startup: Unable to load dynamic library '/alidata/server/php/lib/php/extensions/no-debug-non-zts-20121212/opencc.so' - libopencc.so.2: cannot open shared object file: No such file or directory in Unknown on line 0

我用的是阿里云的ecs。向阿里云下工单他们说不管第三方插件。。

我已经搞了三天了，确实是须要你这个功能。所以才一直没放弃！

/alidata/server/php/lib/php/extensions/no-debug-non-zts-20121212/opencc.so这个文件是存在的。我是不是可能理解为编译功能的。可是为什么提示加载不了呢?

**Comment by NauxLiu** [comment]
根据 [OpenCC](https://github.com/BYVoid/OpenCC#installation-安裝) 项目的安装文档重新安装一下 opencc 吧。

**Comment by NauxLiu** [comment]
问题后续就在这个 issue 里面讨论吧，别再开新的了。以后开 issue 最好在 title 里面问题做简要描述。

**Comment by tooktoo** [comment]
刚才又重装了一次opencc和opencc4php还是不行。提示不能加载。我把我的安装步骤和你说说吧，你看看有没有问体。
clone好后，进入OpenCC目录。
然后make，能执行
再然后我没用sudo make install 直接用的是make install 因前天用sudo make install一直报错，我在网上查了好资料说用root登陆的不用给sudo  所以我是用make install安装的

再安装opencc4php先phpize他能找到  
然后直接是./configure (我clone的目录在是/root/opencc。我看安装opencc时是装在usr下的。所以这个后面没有加参数，。。。后面尝试改./configure 改成/root/opencc也不行)
最后直接用这个make
再跑去改php.ini最后一行加extension=opencc.so

然后重启httpd 
php -m | grep open

就提示上面的错误了。只看到一个openssl是开启的

**Comment by tooktoo** [comment]
搞定了。以上步骤全没错。该死的baidu。用google二分钟搞定了

**Comment by leo-yi** [comment]
兄弟怎么搞定的？不说一个？

**Comment by TrimMine** [comment]
lib64没有libopencc.so.2

用这个命令解决 
ln -s /usr/lib/libopencc.so.2  /usr/lib64/libopencc.so.2

ubantu用
sudo ln -s /usr/lib/libopencc.so.2  /usr/lib64/libopencc.so.2

**Comment by TrimMine** [comment]
真是百度都是错的 google一下就ok了
