### ISSUE TITLE
fatal: Could not read from remote repository.

### ISSUE THREAD

**Issue by luoben4040** [nauxliu/opencc4php#59]
Cloning into 'opencc4php'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by Zola** [comment]
some situations 
`# git clone git@github.com:NauxLiu/opencc4php.git --depth 1
Cloning into 'opencc4php'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
`
add ssh agent failed too

`# git clone git@github.com:NauxLiu/opencc4php.git --depth 1
fatal: destination path 'opencc4php' already exists and is not an empty directory.`

can anyone help?

**Comment by nauxliu** [comment]
This might related to that I changed my GitHub name, I just updated the README.md to reflect it.

@Zola 
```
fatal: destination path 'opencc4php' already exists and is not an empty directory.
```
As for this issue, just the message pointed out, the project is already cloned to your computer. Anyway, you could delete the old folder and try again.
