### ISSUE TITLE
非常好用啊，就是用了些时间，发现占内存比较严重、

### ISSUE THREAD

**Issue by tooktoo** [NauxLiu/opencc4php#6]
可能我转换的东西比较多。差不多能吃掉我1.5G的内存。。。有点汗！

能不能搞个win下的。我看到opencc有win下的。这东西C搞的不会。

所以过求助了，如果有win下的就好了！因为我是php要用呵呵~！

**Comment by NauxLiu** [comment]
抱歉，目前没有开发 Win 版本的想法。
内存占用严重的问题，请确保每次使用完有使用 `opencc_close` 关闭句柄。如果还是严重，那就是 OpenCC 自身的内存占用了。
