### ISSUE TITLE
PHP7 Support

### ISSUE THREAD

**Issue by shtse8** [NauxLiu/opencc4php#8]
Latest PHP7 is released.

**Comment by NauxLiu** [comment]
Already supported, see: https://github.com/NauxLiu/opencc4php/pull/7

**Comment by shtse8** [comment]
I mean the official final version, but not the beta nightly version.
PHP 7.0.0 is released at 2015.12.3 and PHP 7.0.1 is 2015.12.17.

#7  is old and cannot be used.
you can check it.
I've forked the project and spent a hour to fix.
https://github.com/shtse8/opencc4php7-New
