### ISSUE TITLE
New Official PHP7 Support ( Not the Nightly PHP7 )

### ISSUE THREAD

**Issue by shtse8** [NauxLiu/opencc4php#9]
For those who want to use opencc4php for php7 before this project is been updated.
I have added the support by myself, but I am new in this field.
So I don't know how to make it backward-compatible.
Here is my forked project. I have tested and am using it now.
Hope everything is fine and you would like it.
https://github.com/shtse8/opencc4php7-New

I hope this project can be updated soon so that everyone can benefit from it.
Thanks.

**Comment by NauxLiu** [comment]
Thanks, Can you send a PR?

**Comment by shtse8** [comment]
Yes, I have created and added the PHP5 backward-compatible.
